COMMON_GROUND_TEXTURE_ID = 0
GRID_SIZE = 32
MAX_SIZE = 100

[[biomes]]
i_end = 74
i_init = 66
j_end = 60
j_init = 45
type = 'Forest'

[[cities]]
i_end = 63
i_init = 37
j_end = 60
j_init = 45
type = 'City'

[[collidable_cells]]
i = 39
j = 52

[[collidable_cells]]
i = 39
j = 53

[[collidable_cells]]
i = 40
j = 52

[[collidable_cells]]
i = 40
j = 53

[[collidable_cells]]
i = 41
j = 48

[[collidable_cells]]
i = 41
j = 49

[[collidable_cells]]
i = 41
j = 52

[[collidable_cells]]
i = 41
j = 53

[[collidable_cells]]
i = 41
j = 62

[[collidable_cells]]
i = 41
j = 63

[[collidable_cells]]
i = 42
j = 48

[[collidable_cells]]
i = 42
j = 49

[[collidable_cells]]
i = 42
j = 52

[[collidable_cells]]
i = 42
j = 53

[[collidable_cells]]
i = 42
j = 62

[[collidable_cells]]
i = 42
j = 63

[[collidable_cells]]
i = 45
j = 46

[[collidable_cells]]
i = 45
j = 47

[[collidable_cells]]
i = 46
j = 46

[[collidable_cells]]
i = 46
j = 47

[[collidable_cells]]
i = 50
j = 45

[[collidable_cells]]
i = 50
j = 46

[[collidable_cells]]
i = 51
j = 45

[[collidable_cells]]
i = 51
j = 46

[[collidable_cells]]
i = 52
j = 45

[[collidable_cells]]
i = 52
j = 46

[[collidable_cells]]
i = 53
j = 45

[[collidable_cells]]
i = 53
j = 46

[[collidable_cells]]
i = 58
j = 50

[[collidable_cells]]
i = 58
j = 51

[[collidable_cells]]
i = 58
j = 52

[[collidable_cells]]
i = 59
j = 47

[[collidable_cells]]
i = 59
j = 48

[[collidable_cells]]
i = 59
j = 50

[[collidable_cells]]
i = 59
j = 51

[[collidable_cells]]
i = 59
j = 52

[[collidable_cells]]
i = 59
j = 53

[[collidable_cells]]
i = 60
j = 47

[[collidable_cells]]
i = 60
j = 48

[[collidable_cells]]
i = 60
j = 50

[[collidable_cells]]
i = 60
j = 51

[[collidable_cells]]
i = 60
j = 52

[[collidable_cells]]
i = 61
j = 49

[[collidable_cells]]
i = 61
j = 50

[[collidable_cells]]
i = 61
j = 51

[[collidable_cells]]
i = 62
j = 49

[[collidable_cells]]
i = 62
j = 50

[[collidable_cells]]
i = 62
j = 51

[[collidable_cells]]
i = 62
j = 52

[[collidable_cells]]
i = 63
j = 49

[[collidable_cells]]
i = 63
j = 50

[[collidable_cells]]
i = 63
j = 51

[[collidable_cells]]
i = 68
j = 45

[[collidable_cells]]
i = 68
j = 46

[[collidable_cells]]
i = 74
j = 46

[[collidable_cells]]
i = 74
j = 47

[[textures]]
i = 38
j = 41
priority = 1
txt_id = 2

[[textures]]
i = 42
j = 39
priority = 1
txt_id = 2

[[textures]]
i = 56
j = 40
priority = 1
txt_id = 2

[[textures]]
i = 38
j = 55
priority = 1
txt_id = 2

[[textures]]
i = 50
j = 45
priority = 1
txt_id = 18

[[textures]]
i = 39
j = 52
priority = 1
txt_id = 18

[[textures]]
i = 61
j = 48
priority = 1
txt_id = 20

[[textures]]
i = 58
j = 49
priority = 1
txt_id = 20

[[textures]]
i = 40
j = 47
priority = 0
txt_id = 0

[[textures]]
i = 39
j = 48
priority = 0
txt_id = 0

[[textures]]
i = 38
j = 49
priority = 0
txt_id = 0

[[textures]]
i = 38
j = 52
priority = 0
txt_id = 0

[[textures]]
i = 38
j = 54
priority = 0
txt_id = 0

[[textures]]
i = 37
j = 57
priority = 0
txt_id = 0

[[textures]]
i = 38
j = 59
priority = 0
txt_id = 0

[[textures]]
i = 40
j = 60
priority = 0
txt_id = 0

[[textures]]
i = 45
j = 60
priority = 0
txt_id = 0

[[textures]]
i = 48
j = 60
priority = 0
txt_id = 0

[[textures]]
i = 54
j = 60
priority = 0
txt_id = 0

[[textures]]
i = 56
j = 59
priority = 0
txt_id = 0

[[textures]]
i = 58
j = 58
priority = 0
txt_id = 0

[[textures]]
i = 60
j = 57
priority = 0
txt_id = 0

[[textures]]
i = 62
j = 56
priority = 0
txt_id = 0

[[textures]]
i = 62
j = 53
priority = 0
txt_id = 0

[[textures]]
i = 62
j = 51
priority = 0
txt_id = 0

[[textures]]
i = 61
j = 49
priority = 0
txt_id = 0

[[textures]]
i = 60
j = 47
priority = 0
txt_id = 0

[[textures]]
i = 59
j = 46
priority = 0
txt_id = 0

[[textures]]
i = 57
j = 45
priority = 0
txt_id = 0

[[textures]]
i = 56
j = 45
priority = 0
txt_id = 0

[[textures]]
i = 54
j = 45
priority = 0
txt_id = 0

[[textures]]
i = 52
j = 45
priority = 0
txt_id = 0

[[textures]]
i = 50
j = 45
priority = 0
txt_id = 0

[[textures]]
i = 48
j = 45
priority = 0
txt_id = 0

[[textures]]
i = 47
j = 46
priority = 0
txt_id = 0

[[textures]]
i = 45
j = 47
priority = 0
txt_id = 0

[[textures]]
i = 44
j = 48
priority = 0
txt_id = 0

[[textures]]
i = 43
j = 50
priority = 0
txt_id = 0

[[textures]]
i = 42
j = 51
priority = 0
txt_id = 0

[[textures]]
i = 43
j = 54
priority = 0
txt_id = 0

[[textures]]
i = 44
j = 55
priority = 0
txt_id = 0

[[textures]]
i = 46
j = 56
priority = 0
txt_id = 0

[[textures]]
i = 48
j = 56
priority = 0
txt_id = 0

[[textures]]
i = 51
j = 60
priority = 0
txt_id = 0

[[textures]]
i = 52
j = 57
priority = 0
txt_id = 0

[[textures]]
i = 53
j = 56
priority = 0
txt_id = 0

[[textures]]
i = 55
j = 56
priority = 0
txt_id = 0

[[textures]]
i = 57
j = 56
priority = 0
txt_id = 0

[[textures]]
i = 58
j = 54
priority = 0
txt_id = 0

[[textures]]
i = 59
j = 52
priority = 0
txt_id = 0

[[textures]]
i = 59
j = 51
priority = 0
txt_id = 0

[[textures]]
i = 57
j = 49
priority = 0
txt_id = 0

[[textures]]
i = 56
j = 49
priority = 0
txt_id = 0

[[textures]]
i = 55
j = 49
priority = 0
txt_id = 0

[[textures]]
i = 52
j = 49
priority = 0
txt_id = 0

[[textures]]
i = 51
j = 49
priority = 0
txt_id = 0

[[textures]]
i = 48
j = 50
priority = 0
txt_id = 0

[[textures]]
i = 47
j = 51
priority = 0
txt_id = 0

[[textures]]
i = 47
j = 53
priority = 0
txt_id = 0

[[textures]]
i = 50
j = 53
priority = 0
txt_id = 0

[[textures]]
i = 52
j = 53
priority = 0
txt_id = 0

[[textures]]
i = 54
j = 53
priority = 0
txt_id = 0

[[textures]]
i = 56
j = 52
priority = 0
txt_id = 0

[[textures]]
i = 35
j = 55
priority = 0
txt_id = 0

[[textures]]
i = 35
j = 53
priority = 0
txt_id = 0

[[textures]]
i = 35
j = 51
priority = 0
txt_id = 0

[[textures]]
i = 66
j = 60
priority = 0
txt_id = 0

[[textures]]
i = 68
j = 60
priority = 0
txt_id = 0

[[textures]]
i = 71
j = 59
priority = 0
txt_id = 0

[[textures]]
i = 71
j = 58
priority = 0
txt_id = 0

[[textures]]
i = 71
j = 57
priority = 0
txt_id = 0

[[textures]]
i = 67
j = 56
priority = 0
txt_id = 0

[[textures]]
i = 65
j = 58
priority = 0
txt_id = 0

[[textures]]
i = 63
j = 60
priority = 0
txt_id = 0

[[textures]]
i = 62
j = 61
priority = 0
txt_id = 0

[[textures]]
i = 67
j = 54
priority = 0
txt_id = 0

[[textures]]
i = 67
j = 51
priority = 0
txt_id = 0

[[textures]]
i = 65
j = 49
priority = 0
txt_id = 0

[[textures]]
i = 64
j = 48
priority = 0
txt_id = 0

[[textures]]
i = 63
j = 46
priority = 0
txt_id = 0

[[textures]]
i = 66
j = 46
priority = 0
txt_id = 0

[[textures]]
i = 68
j = 46
priority = 0
txt_id = 0

[[textures]]
i = 71
j = 47
priority = 0
txt_id = 0

[[textures]]
i = 72
j = 49
priority = 0
txt_id = 0

[[textures]]
i = 72
j = 52
priority = 0
txt_id = 0

[[textures]]
i = 73
j = 53
priority = 0
txt_id = 0

[[textures]]
i = 71
j = 53
priority = 0
txt_id = 0

[[textures]]
i = 70
j = 50
priority = 0
txt_id = 0

[[textures]]
i = 65
j = 45
priority = 0
txt_id = 0

[[textures]]
i = 65
j = 44
priority = 0
txt_id = 0

[[textures]]
i = 70
j = 44
priority = 0
txt_id = 0

[[textures]]
i = 74
j = 44
priority = 0
txt_id = 0

[[textures]]
i = 75
j = 46
priority = 0
txt_id = 0

[[textures]]
i = 76
j = 48
priority = 0
txt_id = 0

[[textures]]
i = 77
j = 50
priority = 0
txt_id = 0

[[textures]]
i = 76
j = 54
priority = 0
txt_id = 0

[[textures]]
i = 76
j = 56
priority = 0
txt_id = 0

[[textures]]
i = 75
j = 58
priority = 0
txt_id = 0

[[textures]]
i = 73
j = 60
priority = 0
txt_id = 0

[[textures]]
i = 74
j = 58
priority = 0
txt_id = 0

[[textures]]
i = 63
j = 42
priority = 0
txt_id = 0

[[textures]]
i = 65
j = 37
priority = 1
txt_id = 21

[[textures]]
i = 71
j = 38
priority = 1
txt_id = 21
