# Body frames 
[Body.Down]
frames = [
    { x = 3, y = 14, w = 19, h = 29 },
    { x = 29, y = 14, w = 18, h = 29 },
    { x = 54, y = 14, w = 18, h = 29 },
    { x = 78, y = 14, w = 19, h = 29 },
    { x = 103, y = 14, w = 18, h = 29 },
    { x = 128, y = 14, w = 18, h = 29 }
]

[Body.Up]
frames = [
    { x = 3, y = 58, w = 19, h = 30 },
    { x = 28, y = 58, w = 19, h = 30 },
    { x = 53, y = 58, w = 19, h = 30 },
    { x = 78, y = 58, w = 19, h = 30 },
    { x = 103, y = 58, w = 19, h = 30 },
    { x = 128, y = 58, w = 19, h = 30 }
]

[Body.Left]
frames = [
    { x = 6, y = 104, w = 12, h = 29 },
    { x = 26, y = 104, w = 17, h = 29 },
    { x = 51, y = 104, w = 17, h = 29 },
    { x = 76, y = 104, w = 17, h = 29 },
    { x = 106, y = 104, w = 12, h = 29 }
]

[Body.Right]
frames = [
    { x = 6, y = 149, w = 12, h = 29 },
    { x = 31, y = 149, w = 18, h = 29 },
    { x = 56, y = 149, w = 17, h = 29 },
    { x = 81, y = 149, w = 17, h = 29 },
    { x = 106, y = 149, w = 12, h = 29 }
]


# Head frames 
[Head.Down]
point = { x = 0, y = 0, w = 16, h = 16 }

[Head.Right]
point = { x = 17, y = 0, w = 16, h = 16 }

[Head.Left]
point = { x = 34, y = 0, w = 16, h = 16 }

[Head.Up]
point = { x = 51, y = 0, w = 16, h = 16 }

[Zombie.Down]
frames = [
    { x = 3, y = 14, w = 19, h = 29 },
    { x = 29, y = 14, w = 18, h = 29 },
    { x = 54, y = 14, w = 18, h = 29 },
    { x = 78, y = 14, w = 19, h = 29 },
    { x = 103, y = 14, w = 18, h = 29 },
    { x = 128, y = 14, w = 18, h = 29 }
]

[Zombie.Up]
frames = [
    { x = 3, y = 58, w = 19, h = 30 },
    { x = 28, y = 58, w = 19, h = 30 },
    { x = 53, y = 58, w = 19, h = 30 },
    { x = 78, y = 58, w = 19, h = 30 },
    { x = 103, y = 58, w = 19, h = 30 },
    { x = 128, y = 58, w = 19, h = 30 }
]

[Zombie.Left]
frames = [
    { x = 6, y = 104, w = 12, h = 29 },
    { x = 26, y = 104, w = 17, h = 29 },
    { x = 51, y = 104, w = 17, h = 29 },
    { x = 76, y = 104, w = 17, h = 29 },
    { x = 106, y = 104, w = 12, h = 29 }
]

[Zombie.Right]
frames = [
    { x = 6, y = 149, w = 12, h = 29 },
    { x = 31, y = 149, w = 18, h = 29 },
    { x = 56, y = 149, w = 17, h = 29 },
    { x = 81, y = 149, w = 17, h = 29 },
    { x = 106, y = 149, w = 12, h = 29 }
]

[Skeleton.Down]
frames = [
    { x = 18, y = 14, w = 19, h = 30 },
    { x = 117, y = 14, w = 18, h = 30 },
    { x = 214, y = 14, w = 18, h = 30 },
    { x = 308, y = 14, w = 19, h = 30 },
    { x = 409, y = 14, w = 18, h = 30 },
    { x = 504, y = 14, w = 18, h = 30 }
]

[Skeleton.Up]
frames = [
    { x = 18, y = 58, w = 19, h = 31 },
    { x = 117, y = 58, w = 18, h = 31 },
    { x = 214, y = 58, w = 18, h = 31 },
    { x = 308, y = 58, w = 19, h = 31 },
    { x = 409, y = 58, w = 18, h = 31 },
    { x = 504, y = 58, w = 18, h = 31 }
]

[Skeleton.Left]
frames = [
    { x = 36, y = 104, w = 12, h = 30 },
    { x = 108, y = 104, w = 17, h = 30 },
    { x = 205, y = 104, w = 17, h = 30 },
    { x = 309, y = 104, w = 17, h = 30 },
    { x = 428, y = 104, w = 12, h = 30 }
]

[Skeleton.Right]
frames = [
    { x = 27, y = 149, w = 12, h = 30 },
    { x = 127, y = 149, w = 18, h = 30 },
    { x = 211, y = 149, w = 17, h = 30 },
    { x = 311, y = 149, w = 17, h = 30 },
    { x = 421, y = 149, w = 12, h = 30 }
]

[Spider.Down]
frames = [
    { x = 3, y = 1, w = 62, h = 42 },
    { x = 68, y = 1, w = 62, h = 42 },
    { x = 133, y = 1, w = 61, h = 42 },
    { x = 199, y = 1, w = 61, h = 42 }
]

[Spider.Up]
frames = [
    { x = 3, y = 44, w = 62, h = 42 },
    { x = 68, y = 44, w = 62, h = 42 },
    { x = 133, y = 44, w = 61, h = 42 },
    { x = 199, y = 44, w = 61, h = 42 }
]

[Spider.Left]
frames = [
    { x = 3, y = 87, w = 59, h = 41 },
    { x = 68, y = 87, w = 59, h = 41 },
    { x = 133, y = 87, w = 59, h = 41 },
    { x = 199, y = 87, w = 59, h = 41 }
]

[Spider.Right]
frames = [
    { x = 5, y = 130, w = 59, h = 41 },
    { x = 70, y = 130, w = 59, h = 41 },
    { x = 135, y = 130, w = 59, h = 41 },
    { x = 201, y = 130, w = 59, h = 41 }
]

[Golem.Down]
frames = [
    { x = 11, y = 8, w = 34, h = 47 },
    { x = 55, y = 8, w = 35, h = 47 },
    { x = 101, y = 8, w = 36, h = 47 },
    { x = 148, y = 8, w = 36, h = 47 },
    { x = 194, y = 8, w = 35, h = 47 },
    { x = 239, y = 8, w = 35, h = 47 }
]

[Golem.Up]
frames = [
    { x = 11, y = 57, w = 34, h = 46 },
    { x = 55, y = 57, w = 36, h = 46 },
    { x = 103, y = 57, w = 34, h = 46 },
    { x = 149, y = 57, w = 35, h = 46 },
    { x = 196, y = 57, w = 35, h = 46 },
    { x = 241, y = 57, w = 35, h = 46 }
]

[Golem.Left]
frames = [
    { x = 11, y = 107, w = 30, h = 46 },
    { x = 57, y = 107, w = 24, h = 46 },
    { x = 104, y = 107, w = 21, h = 46 },
    { x = 147, y = 107, w = 29, h = 46 },
    { x = 195, y = 107, w = 25, h = 46 },
    { x = 241, y = 107, w = 20, h = 46 }
]

[Golem.Right]
frames = [
    { x = 14, y = 156, w = 20, h = 46 },
    { x = 59, y = 156, w = 25, h = 46 },
    { x = 102, y = 156, w = 29, h = 46 },
    { x = 151, y = 156, w = 21, h = 46 },
    { x = 196, y = 156, w = 24, h = 46 },
    { x = 241, y = 156, w = 30, h = 46 }
]

[GreatReamer.Down]
frames = [
    { x = 11, y = 8, w = 45, h = 45 },
    { x = 71, y = 8, w = 45, h = 45 },
    { x = 131, y = 8, w = 45, h = 45 },
    { x = 191, y = 8, w = 45, h = 45 },
    { x = 251, y = 8, w = 45, h = 45 }
]

[GreatReamer.Up]
frames = [
    { x = 15, y = 52, w = 41, h = 44 },
    { x = 68, y = 52, w = 44, h = 44 },
    { x = 130, y = 52, w = 43, h = 44 },
    { x = 189, y = 52, w = 44, h = 44 },
    { x = 250, y = 52, w = 43, h = 44 }
]

[GreatReamer.Left]
frames = [
    { x = 13, y = 99, w = 48, h = 46 },
    { x = 70, y = 99, w = 49, h = 46 },
    { x = 126, y = 99, w = 50, h = 46 },
    { x = 182, y = 99, w = 50, h = 46 },
    { x = 241, y = 99, w = 48, h = 46 }
]

[GreatReamer.Right]
frames = [
    { x = 10, y = 145, w = 44, h = 44 },
    { x = 67, y = 145, w = 44, h = 44 },
    { x = 125, y = 145, w = 45, h = 44 },
    { x = 183, y = 145, w = 45, h = 44 },
    { x = 241, y = 145, w = 44, h = 44 }
]


[Giant.Down]
frames = [
    { x = 15, y = 26, w = 24, h = 45 },
    { x = 49, y = 26, w = 23, h = 45 },
    { x = 83, y = 26, w = 23, h = 45 },
    { x = 117, y = 26, w = 24, h = 45 },
    { x = 151, y = 26, w = 23, h = 45 },
    { x = 185, y = 26, w = 23, h = 45 }
]

[Giant.Up]
frames = [
    { x = 15, y = 82, w = 24, h = 45 },
    { x = 49, y = 82, w = 23, h = 45 },
    { x = 83, y = 82, w = 23, h = 45 },
    { x = 117, y = 82, w = 24, h = 45 },
    { x = 151, y = 82, w = 23, h = 45 },
    { x = 185, y = 82, w = 23, h = 45 }
]

[Giant.Left]
frames = [
    { x = 20, y = 138, w = 15, h = 44 },
    { x = 45, y = 138, w = 21, h = 44 },
    { x = 79, y = 138, w = 22, h = 44 },
    { x = 117, y = 138, w = 17, h = 44 },
    { x = 152, y = 138, w = 16, h = 44 }
]

[Giant.Right]
frames = [
    { x = 21, y = 194, w = 15, h = 44 },
    { x = 55, y = 194, w = 22, h = 44 },
    { x = 89, y = 194, w = 21, h = 44 },
    { x = 126, y = 194, w = 17, h = 44 },
    { x = 153, y = 194, w = 16, h = 44 }
]

[Elf.Down]
frames = [
    { x = 11, y = 10, w = 22, h = 32 },
    { x = 43, y = 10, w = 22, h = 32 },
    { x = 75, y = 10, w = 22, h = 32 },
    { x = 107, y = 10, w = 22, h = 32 },
    { x = 139, y = 10, w = 22, h = 32 },
    { x = 171, y = 10, w = 22, h = 32 },
    { x = 203, y = 10, w = 22, h = 32 },
    { x = 235, y = 10, w = 22, h = 32 }
]

[Elf.Up]
frames = [
    { x = 11, y = 50, w = 22, h = 32 },
    { x = 43, y = 50, w = 22, h = 32 },
    { x = 75, y = 50, w = 22, h = 32 },
    { x = 107, y = 50, w = 22, h = 32 },
    { x = 139, y = 50, w = 22, h = 32 },
    { x = 171, y = 50, w = 22, h = 32 },
    { x = 203, y = 50, w = 22, h = 32 },
    { x = 235, y = 50, w = 22, h = 32 }
]

[Elf.Left]
frames = [
    { x = 15, y = 90, w = 15, h = 32 },
    { x = 46, y = 90, w = 16, h = 32 },
    { x = 77, y = 90, w = 17, h = 32 },
    { x = 110, y = 90, w = 14, h = 32 },
    { x = 142, y = 90, w = 15, h = 32 },
    { x = 172, y = 90, w = 18, h = 32 },
    { x = 205, y = 90, w = 17, h = 32 },
    { x = 238, y = 90, w = 14, h = 32 }
]

[Elf.Right]
frames = [
    { x = 14, y = 130, w = 15, h = 32 },
    { x = 44, y = 130, w = 18, h = 32 },
    { x = 75, y = 130, w = 17, h = 32 },
    { x = 108, y = 130, w = 14, h = 32 },
    { x = 143, y = 130, w = 15, h = 32 },
    { x = 174, y = 130, w = 16, h = 32 },
    { x = 206, y = 130, w = 17, h = 32 },
    { x = 238, y = 130, w = 14, h = 32 }
]
[SpecialSpider.Down]
frames = [
    { x = 32, y = 78, w = 62, h = 56 },
    { x = 221, y = 78, w = 63, h = 51 },
    { x = 411, y = 80, w = 61, h = 53 },
    { x = 591, y = 79, w = 63, h = 53 },
    { x = 778, y = 81, w = 63, h = 51 }
]

[SpecialSpider.Up]
frames = [
    { x = 30, y = 260, w = 63, h = 54 },
    { x = 215, y = 261, w = 63, h = 55 },
    { x = 409, y = 261, w = 61, h = 55 },
    { x = 596, y = 261, w = 63, h = 54 },
    { x = 785, y = 260, w = 63, h = 55 }
]

[SpecialSpider.Left]
frames = [
    { x = 11, y = 460, w = 82, h = 48 },
    { x = 197, y = 461, w = 80, h = 47 },
    { x = 380, y = 459, w = 86, h = 48 },
    { x = 578, y = 459, w = 73, h = 50 },
    { x = 754, y = 459, w = 84, h = 49 }
]

[SpecialSpider.Right]
frames = [
    { x = 17, y = 648, w = 82, h = 49 },
    { x = 207, y = 647, w = 80, h = 49 },
    { x = 387, y = 647, w = 86, h = 49 },
    { x = 588, y = 648, w = 73, h = 49 },
    { x = 764, y = 649, w = 84, h = 48 }
]

[SpecialSkeleton.Down]
frames = [
    { x = 3, y = 3, w = 29, h = 42 },
    { x = 36, y = 3, w = 26, h = 42 },
    { x = 65, y = 3, w = 28, h = 42 },
    { x = 96, y = 3, w = 29, h = 42 },
    { x = 129, y = 3, w = 25, h = 42 },
    { x = 163, y = 3, w = 20, h = 42 }
]

[SpecialSkeleton.Up]
frames = [
    { x = 6, y = 51, w = 20, h = 42 },
    { x = 35, y = 51, w = 27, h = 42 },
    { x = 68, y = 51, w = 21, h = 42 },
    { x = 97, y = 51, w = 23, h = 42 },
    { x = 127, y = 51, w = 26, h = 42 },
    { x = 160, y = 51, w = 23, h = 42 }
]

[SpecialSkeleton.Left]
frames = [
    { x = 4, y = 99, w = 26, h = 42 },
    { x = 34, y = 99, w = 27, h = 42 },
    { x = 66, y = 99, w = 24, h = 42 },
    { x = 99, y = 99, w = 24, h = 42 },
    { x = 131, y = 99, w = 21, h = 42 }
]

[SpecialSkeleton.Right]
frames = [
    { x = 8, y = 147, w = 18, h = 42 },
    { x = 37, y = 147, w = 24, h = 42 },
    { x = 68, y = 147, w = 24, h = 42 },
    { x = 96, y = 147, w = 23, h = 42 },
    { x = 132, y = 147, w = 24, h = 42 }
]

[Orc.Down]
frames = [
    { x = 7, y = 31, w = 46, h = 47 },
    { x = 65, y = 31, w = 43, h = 47 },
    { x = 122, y = 31, w = 42, h = 47 },
    { x = 173, y = 31, w = 46, h = 47 },
    { x = 231, y = 31, w = 44, h = 47 },
    { x = 286, y = 31, w = 43, h = 47 }
]

[Orc.Up]
frames = [
    { x = 9, y = 111, w = 44, h = 46 },
    { x = 65, y = 111, w = 45, h = 46 },
    { x = 121, y = 111, w = 44, h = 46 },
    { x = 175, y = 111, w = 44, h = 46 },
    { x = 231, y = 111, w = 44, h = 46 },
    { x = 287, y = 111, w = 44, h = 46 }
]

[Orc.Left]
frames = [
    { x = 18, y = 211, w = 26, h = 45 },
    { x = 67, y = 211, w = 33, h = 45 },
    { x = 123, y = 211, w = 36, h = 45 },
    { x = 188, y = 211, w = 26, h = 45 },
    { x = 240, y = 211, w = 27, h = 45 }
]

[Orc.Right]
frames = [
    { x = 13, y = 308, w = 27, h = 45 },
    { x = 66, y = 308, w = 26, h = 45 },
    { x = 121, y = 308, w = 36, h = 45 },
    { x = 180, y = 308, w = 33, h = 45 },
    { x = 237, y = 308, w = 26, h = 45 }
]
