# Body frames 
[Body.Down]
frames = [
    { x = 3, y = 14, w = 19, h = 29 },
    { x = 29, y = 14, w = 18, h = 29 },
    { x = 54, y = 14, w = 18, h = 29 },
    { x = 78, y = 14, w = 19, h = 29 },
    { x = 103, y = 14, w = 18, h = 29 },
    { x = 128, y = 14, w = 18, h = 29 }
]

[Body.Up]
frames = [
    { x = 3, y = 58, w = 19, h = 30 },
    { x = 28, y = 58, w = 19, h = 30 },
    { x = 53, y = 58, w = 19, h = 30 },
    { x = 78, y = 58, w = 19, h = 30 },
    { x = 103, y = 58, w = 19, h = 30 },
    { x = 128, y = 58, w = 19, h = 30 }
]

[Body.Left]
frames = [
    { x = 6, y = 104, w = 12, h = 29 },
    { x = 26, y = 104, w = 17, h = 29 },
    { x = 51, y = 104, w = 17, h = 29 },
    { x = 76, y = 104, w = 17, h = 29 },
    { x = 106, y = 104, w = 12, h = 29 }
]

[Body.Right]
frames = [
    { x = 6, y = 149, w = 12, h = 29 },
    { x = 31, y = 149, w = 18, h = 29 },
    { x = 56, y = 149, w = 17, h = 29 },
    { x = 81, y = 149, w = 17, h = 29 },
    { x = 106, y = 149, w = 12, h = 29 }
]


# Head frames 
[Head.Down]
point = { x = 0, y = 0, w = 16, h = 16 }

[Head.Right]
point = { x = 17, y = 0, w = 16, h = 16 }

[Head.Left]
point = { x = 34, y = 0, w = 16, h = 16 }

[Head.Up]
point = { x = 51, y = 0, w = 16, h = 16 }

[Zombie.Down]
frames = [
    { x = 3, y = 14, w = 19, h = 29 },
    { x = 29, y = 14, w = 18, h = 29 },
    { x = 54, y = 14, w = 18, h = 29 },
    { x = 78, y = 14, w = 19, h = 29 },
    { x = 103, y = 14, w = 18, h = 29 },
    { x = 128, y = 14, w = 18, h = 29 }
]

[Zombie.Up]
frames = [
    { x = 3, y = 58, w = 19, h = 30 },
    { x = 28, y = 58, w = 19, h = 30 },
    { x = 53, y = 58, w = 19, h = 30 },
    { x = 78, y = 58, w = 19, h = 30 },
    { x = 103, y = 58, w = 19, h = 30 },
    { x = 128, y = 58, w = 19, h = 30 }
]

[Zombie.Left]
frames = [
    { x = 6, y = 104, w = 12, h = 29 },
    { x = 26, y = 104, w = 17, h = 29 },
    { x = 51, y = 104, w = 17, h = 29 },
    { x = 76, y = 104, w = 17, h = 29 },
    { x = 106, y = 104, w = 12, h = 29 }
]

[Zombie.Right]
frames = [
    { x = 6, y = 149, w = 12, h = 29 },
    { x = 31, y = 149, w = 18, h = 29 },
    { x = 56, y = 149, w = 17, h = 29 },
    { x = 81, y = 149, w = 17, h = 29 },
    { x = 106, y = 149, w = 12, h = 29 }
]